#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/resources/config/dev.php';
require __DIR__.'/src/app.php';
/*
 * Needed to prevent:
 *
 * [InvalidArgumentException]
 *   Identifier "security.authentication_providers" is not defined.
 */
$app->boot();

$console = require __DIR__.'/src/console.php';
$console->run();

